version: '3.8'

services:
  app:
    build: .
    container_name: nestjs_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: nest
      DB_PASSWORD: nest
      DB_DATABASE: nestdb
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: nestjs_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nestdb
      MYSQL_USER: nest
      MYSQL_PASSWORD: nest
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
